### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by Morb0** [grammyjs/nestjs#10]
Module creates instance of bot and immediately call async `.start()` and then service search all decorators and try register to bot instance. But you can't register a new handlers after starting bot. 
Because of that each run is random, whether the service has time to register commands before `.start` patches `.use`.
https://github.com/grammyjs/nestjs/blob/ab2f5ce004dab05d7cecc788ca6be6d2d68ff202/packages/grammy-nestjs/src/utils/create-bot-factory.util.ts#L17-L20

**Comment by drmikecrowe** [comment]
Proposal:  Would passing in a setup callback be acceptable?

```ts
  if (!options.useWebhook) {
    log('pollingOptions: ', options.pollingOptions)
    if (options.botSetup) {
      await options.botSetup(bot)
    }
    bot.start(options.pollingOptions || {})
  }
```

The alternative is something like:

```ts
  if (!options.useWebhook) {
    log('pollingOptions: ', options.pollingOptions)
    if (!options.autoStart) {
      bot.start(options.pollingOptions || {})
    }
  }
```

Which would be a better solution for you?
