### ISSUE TITLE
Lodash dependency missing in package.json

### ISSUE THREAD

**Issue by liquidautumn** [grammyjs/nestjs#14]
Lodash is referenced here:
https://github.com/grammyjs/nestjs/blob/73d96888a74560417a2692deb4f3c68300538d20/packages/grammy-nestjs/src/services/base-explorer.service.ts#L4

But not added to dependencies.

**Comment by drmikecrowe** [comment]
How the (bleep) that I miss that?? thanks, working on a fix

**Comment by drmikecrowe** [comment]
https://github.com/grammyjs/nestjs/blob/eeedb1cd33b453aa82915ae2e345cd2242e95b01/packages/grammy-nestjs/CHANGELOG.md#031-2022-06-26
