### ISSUE TITLE
NestJS v9 upgrade

### ISSUE THREAD

**Issue by NarHakobyan** [grammyjs/nestjs#18]
What's new. https://trilon.io/blog/nestjs-9-is-now-available
Migration. https://docs.nestjs.com/migration-guide

**Comment by yn4v4s** [comment]
I just made a PR to close this, I hope it gets reviewed/merged soon, this is the only thing holding me back from moving from telegraf to grammY

**Comment by solidprinciples** [comment]
@yn4v4s - was this published? Getting this when installing with near-latest nestjs:

`npm ERR! Found: @nestjs/common@9.1.4
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^9.0.8" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^8.0.0" from @grammyjs/nestjs@0.3.1
npm ERR! node_modules/@grammyjs/nestjs
npm ERR!   @grammyjs/nestjs@"^0.3.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry`

**Comment by NarHakobyan** [comment]
@drmikecrowe could you please release patch version? :)
