### ISSUE TITLE
How could I add i18n middleware?

### ISSUE THREAD

**Issue by felinto-dev** [grammyjs/nestjs#22]
Is there an example of how to use i18n as middleware?

![image](https://user-images.githubusercontent.com/32253743/194540718-1b0dfcda-2436-4d2c-9d0b-5c16f9f493df.png)

I am receiving this error:
![image](https://user-images.githubusercontent.com/32253743/194540758-2b5ba996-b34e-4541-ab0c-d0c3fd967273.png)

**Comment by KnorpelSenf** [comment]
By `n8n`, do you mean `i18n`?

**Comment by felinto-dev** [comment]
> By `n8n`, do you mean `i18n`?

lol, yes
I changed the title

**Comment by solidprinciples** [comment]
@felinto-dev - are you still facing this issue? I remember someone facing this issue in the telegram group for grammY - helped resolve it there.

Let me know if you need help with this further and I can provide an example.
