### ISSUE TITLE
Is middleware woking? 

### ISSUE THREAD

**Issue by stPitty** [grammyjs/nestjs#27]
Im using async configuration and want to use session:

```typescript
createGrammyOptions(): GrammyModuleOptions {
    return {
      token: myToken,
      middlewares: [session({ initial: () => ({ pizzaCount: 0 }) })],
    };
  }
}
```

Use this in app.module for import: 

```typescript
NestjsGrammyModule.forRootAsync({
  useClass: GrammyConfigService,
}),
```

But its not working. I had tried create custom middleware and it still didnt work.
I just catch nothing in ctx:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/85024641/199610867-350e75f2-694e-405a-9515-ee3cb08dab6a.png">

**Comment by KnorpelSenf** [comment]
Is this a question or a bug report? Either way, you need to elaborate what you mean by “not working.”

**Comment by Morb0** [comment]
No, they're not working. For some reason, lines for register middlewares were just deleted and now that useless field...
https://github.com/grammyjs/nestjs/commit/93d8f8335b567979d0a5729d50dff07df36f0ee1#diff-cb28a0c29c88963748f1d370d740da14e5bbf732bd912ab8b34dca8a686d1acd

**Comment by KnorpelSenf** [comment]
@drmikecrowe and @solidprinciples who maintain this repo are both relatively inactive at the time. Feel free to fix things up and help getting this project back on track, until hopefully they return.

**Comment by solidprinciples** [comment]
PR #33 should fix this.
