### ISSUE TITLE
Question: Webhook URL

### ISSUE THREAD

**Issue by NarHakobyan** [grammyjs/nestjs#28]
Hi Guys, I wanted to give a try your lib but couldn't reach to webhook url part, How can I figure out what is exact url of webhook so I can pass it to telegram.

    consumer.apply(webhookCallback(this.bot, 'express')).forRoutes('*');

**Comment by solidprinciples** [comment]
Hey @NarHakobyan - I am not too familiar with the express webhook portion. Perhaps @drmikecrowe could help clarify? :)

It may also help me if you could give a more complete example to help - thanks!

**Comment by KnorpelSenf** [comment]
The URL depends on where you host your bot. Given the above code snippet, the URL path is most likely `/`. What's your FQDN?

**Comment by NarHakobyan** [comment]
Hey everyone, thanks for replying, that was a simple question, it's been fixed after posting here, so if anyone's curious how to define path for bot url with Nestjs here's a basic example.

```typescript
@Module(...)
export class TelegramModule implements NestModule {
  logger = new Logger(TelegramModule.name);

  constructor(@InjectBot() private readonly bot: Bot<Context>) {
    void this.initBot();
  }

  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(webhookCallback(this.bot, 'express'))
      .forRoutes('/telegram/webhook');
    this.logger.log('Webhook Api Configured ...');
  }

  async initBot() {
    this.bot.use(ResponseTime);

    this.logger.log('Started ...');
  }
}

```

webhook URL would be `{baseUrl}/telegram/webhook` so you can pass this to botsettings

**Comment by KnorpelSenf** [comment]
Glad to hear this is solved. I'll close this then :)
