### ISSUE TITLE
forRootAsync is not working

### ISSUE THREAD

**Issue by herenickname** [grammyjs/nestjs#37]
It adds the "Bot" suffix to botName, after which I get:
`ERROR [ExceptionHandler] Nest can't resolve dependencies of the AppBotModule (?). Please make sure that the argument AppBotBot at index [0] is available in the AppBotModule context.`
Where _AppBot_ is my original provided botName.

```ts
NestjsGrammyModule.forRootAsync({
  imports: [ConfigModule],
  inject: [ConfigService],
  useFactory: (configService: ConfigService) => ({
    botName: AppBotName,
    token: configService.get('TELEGRAM_TOKEN'),
    include: [AppBotModule]
  })
}),
AppBotModule
```

```
export const AppBotName = 'AppBot'
```

**Comment by mlmetzner** [comment]
put `botName: AppBotName`  outside of the factory and it should work
