### ISSUE TITLE
Scenes support

### ISSUE THREAD

**Issue by bonkboykz** [grammyjs/nestjs#9]
Hi, thank you for the nestjs support!

Just wanted to ask: will this module support scenes and is there any way to prompt user for an answer at the moment?

**Comment by drmikecrowe** [comment]
This repo simply adds [NestJS](https://nestjs.com/) support to [grammY](https://grammy.dev).  We do not add additional grammY functionality beyond running in NestJS.

Regarding Scenes, you probably want to [see this issue](https://github.com/grammyjs/grammY/issues/136)

**Comment by IlyaSemenov** [comment]
@bonkboykz You can use [grammy-scenes](https://github.com/IlyaSemenov/grammy-scenes) which I try to keep updated.
